// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xowkmfeztzomplmnhuvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhvd2ttZmV6dHpvbXBsbW5odXZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDQ1MjQsImV4cCI6MjA3Mzc4MDUyNH0.efpMx0eoG866o2olUi70I09f-Iig5nC_hHrS5a2Egyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});